# Windows:
windowrule {
  name = suppress-maximize
  match:class = .*
  suppress_event = maximize
}

windowrule {
  name = Fix Ghosting
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
  no_focus = on
}

windowrule {
  name = PolKit Agent Floating
  match:class = ^(lxqt-policykit-agent)$
  float = on
  center = on
}

windowrule {
  name = tcli floating centered window
  float = on
  match:class = ^(tcli)$
  center = on
  size =  800 600
}

windowrule {
    name = clipse floating window
    match:class = ^(clipse)$
    float = on
    center = on
    size = 622 652
}
# Layers:
layerrule = blur on, match:namespace ^(swaync-control-center)$
