general {
  grab_focus = true
}

cache {
  enabled = false
}

finders {
  default_finder = desktop
  desktop_icons = true
}

ui {
  columns = 2
  rows = 8
  search_text = "Search..."
  window_size = 700 500
}
