# Env:

env = EDITOR,nvim
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
# env = GTK_IM_MODULE,fcitx
env = QT_IM_MODULE,fcitx
env = SDL_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
env = XDG_SCREENSHOTS_DIR,$HOME/Pictures/
env = XDG_SESSION_TYPE,wayland
env = PUB_HOSTED_URL,https://pub.myket.ir
env = FLUTTER_STORAGE_BASE_URL,https://pub.myket.ir
env = ANDROID_HOME,$HOME/dev/Android/Sdk
env = SKIKO_RENDER_API,SOFTWARE
env = GTK_THEME,Adwaita:dark
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = YAZI_CWD_FILE,$HOME/.yazi-cwd
env = PATH,$PATH:$HOME/dev/flutter/bin:$HOME/dev/Android/Sdk/platform-tools:$HOME/dev/Android/Sdk/cmdline-tools/20.0/bin:$HOME/.local/bin
env = FZF_DEFAULT_COMMAND,rg --files --hidden
