# Source:
source = ~/.config/hypr/hyprmonitor.conf
source = ~/.config/hypr/hyprbinds.conf
source = ~/.config/hypr/hyprenvs.conf
source = ~/.config/hypr/hyprautostart.conf
source = ~/.config/hypr/hyprlook.conf
source = ~/.config/hypr/hyprinput.conf
source = ~/.config/hypr/mocha.conf
source = ~/.config/hypr/hyprwinrules.conf
