general {
  hide_cursor = true
}

background {
    monitor = 
    path = screenshot
    blur_passes = 1
    noise = 0.0
}

label {
    monitor = eDP-1
    text = cmd[update:1000] date +"%A, %b %d"
    color = rgba(216, 222, 233, 0.90)
    font_size = 25
    font_family = JetBrainsMono NFP ExtraBold
    position = 0, 350
    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = cmd[update:1000] date +"%T"
    color = rgba(216, 222, 233, 0.90)
    font_size = 120
    font_family = JetBrainsMono NFP ExtraBold
    position = 0, 230
    halign = center
    valign = center
}
