[General]
__userfile__=true
icon_follow_color_scheme=true
icon_theme=Papirus-Dark
palette_override=false
theme=catppuccin-mocha
tool_bar_icon_size=24
tool_button_style=ToolButtonTextBesideIcon
wallpaper_override=false

[Palette]
base_color=#1e1e2e
highlight_color=#cba6f7
highlighted_text_color=#11111b
link_color=#89b4fa
link_visited_color=#b4befe
text_color=#cdd6f4
tooltip_base_color=#1e1e2e
tooltip_text_color=#cdd6f4
window_color=#181825
window_text_color=#cdd6f4

[Qt]
font="JetBrainsMono NFM,12,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,,0,0"
style=qt5ct-style
